### ISSUE TITLE
Putty Need

### ISSUE THREAD

**Issue by mrstark97** [fdac20/students#61]
Hello,

There seems to be a lot of talk about using putty. Could we not use Visual Studio Code as our IDE? In 340, we could easily work fluently with Github and issue pull, push, and clone commands from the integrated terminal.

Thanks!

**Comment by audrism** [comment]
I am not entirely sure of the capabilities of Visual Studio Code as our IDE. Does it support python? Jupyter notebooks? R?

**Comment by mrstark97** [comment]
Yes sir VS code works with python, Jupyter Notebooks, and R language. So if I have these capabilities am I in the clear in using it?

**Comment by audrism** [comment]
You'll still need port forwarding to store to the database and there is nothing wrong knowing how to use terminal. 
Also, some scripts may require more time and continuous connection. Eventually you will very likely need to use ssh port forwarding.

**Comment by mrstark97** [comment]
VS Code also has a SSH extension that supports port forwarding so I hope I am good lol. I am just more comfortable in VS Code than I am in Putty so I am hoping to use it solely and so far I think I can.

**Comment by audrism** [comment]
No problem then! If you do run into issues, please let me know.
